### ISSUE TITLE
Getting multiple responses for conditions Polygon IO API

### ISSUE THREAD

**Issue by pradeep9843** [polygon-io/client-js#107] opened 2022-11-02 15:16 UTC
Hi Team , We are trying to consume conditions polygon IO API and we are passing the expected parameters (see attached), but the request url / response parameters seems to be very different
![image](https://user-images.githubusercontent.com/117295657/199527784-e1a8189e-d4a4-4f74-aa99-4b8355629652.png)

https://api.polygon.io/v3/reference/conditions?0=x&1=B&10=T&11=T&12=5&13=4&14=h&15=j&16=m&17=n&18=D&19=S&2=4&20=t&21=n&22=v&23=n&24=n&25=K&26=U&27=D&28=_&29=a&3=j&30=p&31=H&4=Q&5=V&6=m&7=4&8=3&9=h&apiKey=xxxxxxxxxxxxxxxx

![image](https://user-images.githubusercontent.com/117295657/199527980-c5cb21e9-ad37-41cf-93f0-b122925d9d5d.png)

Please see the expected output in the below mentioned url
https://polygon.io/docs/stocks/get_v3_reference_conditions

Please find the output  getting  in the attached screenshot ( we are consuming the same API which was provided in the above url but the response is different)

![image](https://user-images.githubusercontent.com/117295657/199528056-55291eb8-eaed-4b68-90b1-8668c9aff5c5.png)

Please do the needful

**Comment by pradeep9843** [comment] 2022-11-16 13:40
Team, Any update?

**Comment by timetraveler328** [comment] 2023-01-20 01:43
@pradeep9843 I believe the issue is that the parameter passed into reference.conditions needs to be an object instead of passing individual parameters for each query element.

It should look something like `await reference.conditions({ asset_class: 'stocks', data_type: 'trades', id: '123', sip: 'CTA', order: 'asc', limit: 10, sort: 'id' })` where each query element is a key to an object

You shouldn't need to pass apiKey in the query since you've initialized the client with it.  We use the spread operator to combine the apiKey passed into the client with the query object before sending the request, which is why your resulting request looked strange, it was spreading the string instead of an object.

We'll add this example to our README as well.  Let us know if this solves it for you.

**Comment by timetraveler328** [comment] 2023-01-24 20:50
Closing this issue as resolved by the solution above. Please feel free to create a new issue if you think there's still something here that needs addressed.

**Closed by timetraveler328** 2023-01-24 20:50 UTC
