### ISSUE TITLE
Incorrect typings for polygon's client JS file.

### ISSUE THREAD

**Issue by cedrichan** [polygon-io/client-js#157] opened 2023-05-01 22:32 UTC
When compiling a node typescript project using Polygon, I get the following error:

```
node_modules/@polygon.io/client-js/dist/main.d.ts:9:5 - error TS2411: Property ''X-Polygon-Edge-User-Agent'' of type 'string | undefined' is not assignable to 'string' index type 'string'.

9     'X-Polygon-Edge-User-Agent'?: string;
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/@polygon.io/client-js/dist/main.d.ts:9
```

The relevant part in `main.d.ts`:
```typescript
import * as websocket from 'websocket';

interface IPolygonQuery {
    [key: string]: string | number | boolean | undefined;
}
interface IPolygonEdgeHeaders extends Record<string, string> {
    'X-Polygon-Edge-ID': string;
    'X-Polygon-Edge-IP-Address': string;
    'X-Polygon-Edge-User-Agent'?: string;
}
declare type IHeaders = IPolygonEdgeHeaders | Record<string, string>;
interface IRequestInit extends RequestInit {
    headers?: IHeaders;
}
declare type IRequestOptions = IRequestInit;
declare type IGet = (path: string, query: IPolygonQuery, options: IRequestOptions) => Promise<any>;
```

It seems to be complaining that a `Record` type cannot have an optional key.

### package.json
```
    "@polygon.io/client-js": "^7.2.2",
    "typescript": "~4.9.3",
```

**Comment by timetraveler328** [comment] 2023-05-15 16:32
@cedrichan thanks for filing this. I've made updates in v7.2.3 that address the issue. I couldn't reproduce, but based on the info you provided I've made that type definition a Partial Record. Let me know if it solves your issue and I'll close this ticket.

**Closed** 2023-05-31 17:55 UTC
